// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace JenkinsTestWeb.localhost {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="JenkinsTestWeb.localhost", ConfigurationName="NumberServiceSoap")]
public interface NumberServiceSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/AddNumbers")]
    int AddNumbers(int number1, int number2);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/AddNumbers", AsyncPattern=true)]
    System.IAsyncResult BeginAddNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState);
    
    int EndAddNumbers(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/SubtractNumbers")]
    int SubtractNumbers(int number1, int number2);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/SubtractNumbers", AsyncPattern=true)]
    System.IAsyncResult BeginSubtractNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState);
    
    int EndSubtractNumbers(System.IAsyncResult result);
}

public interface NumberServiceSoapChannel : NumberServiceSoap, System.ServiceModel.IClientChannel {
}

public class NumberServiceSoapClient : System.ServiceModel.ClientBase<NumberServiceSoap>, NumberServiceSoap {
    
    public NumberServiceSoapClient() {
    }
    
    public NumberServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public NumberServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public NumberServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public NumberServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public int AddNumbers(int number1, int number2) {
        return base.Channel.AddNumbers(number1, number2);
    }
    
    public System.IAsyncResult BeginAddNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginAddNumbers(number1, number2, asyncCallback, userState);
    }
    
    public int EndAddNumbers(System.IAsyncResult result) {
        return base.Channel.EndAddNumbers(result);
    }
    
    public int SubtractNumbers(int number1, int number2) {
        return base.Channel.SubtractNumbers(number1, number2);
    }
    
    public System.IAsyncResult BeginSubtractNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginSubtractNumbers(number1, number2, asyncCallback, userState);
    }
    
    public int EndSubtractNumbers(System.IAsyncResult result) {
        return base.Channel.EndSubtractNumbers(result);
    }
}

[System.ServiceModel.ServiceContractAttribute(Namespace="JenkinsTestWeb.localhost", ConfigurationName="NumberServiceSoap12")]
public interface NumberServiceSoap12 {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/AddNumbers")]
    int AddNumbers(int number1, int number2);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/AddNumbers", AsyncPattern=true)]
    System.IAsyncResult BeginAddNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState);
    
    int EndAddNumbers(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/SubtractNumbers")]
    int SubtractNumbers(int number1, int number2);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://tempuri.org/NumberService/SubtractNumbers", AsyncPattern=true)]
    System.IAsyncResult BeginSubtractNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState);
    
    int EndSubtractNumbers(System.IAsyncResult result);
}

public interface NumberServiceSoap12Channel : NumberServiceSoap12, System.ServiceModel.IClientChannel {
}

public class NumberServiceSoap12Client : System.ServiceModel.ClientBase<NumberServiceSoap12>, NumberServiceSoap12 {
    
    public NumberServiceSoap12Client() {
    }
    
    public NumberServiceSoap12Client(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public NumberServiceSoap12Client(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public NumberServiceSoap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public NumberServiceSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public int AddNumbers(int number1, int number2) {
        return base.Channel.AddNumbers(number1, number2);
    }
    
    public System.IAsyncResult BeginAddNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginAddNumbers(number1, number2, asyncCallback, userState);
    }
    
    public int EndAddNumbers(System.IAsyncResult result) {
        return base.Channel.EndAddNumbers(result);
    }
    
    public int SubtractNumbers(int number1, int number2) {
        return base.Channel.SubtractNumbers(number1, number2);
    }
    
    public System.IAsyncResult BeginSubtractNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginSubtractNumbers(number1, number2, asyncCallback, userState);
    }
    
    public int EndSubtractNumbers(System.IAsyncResult result) {
        return base.Channel.EndSubtractNumbers(result);
    }
}
